version: 0.0
os: linux
files:
  - source: /
    destination: /app/world_deploy
#permissions:  # CodeDeploy에서 EC2서버로 넘겨준 파일들을 모두 ec2-user권한을 갖도록 변경
#  - object: /
#    owner: ec2-user
#    group: ec2-user
#  - object: /app/world_deploy/shell/*.sh
#    mode: 744
#    owner: ec2-user
#    group: ec2-user
#    type:
#      - file
hooks:
  ApplicationStop:
    - location: shell/100.ApplicationStop.sh
      timeout: 60
      runas: root
  #  BeforeInstall:
  #    - location: shell/110.BeforeInstall.sh
  #      timeout: 60
  #      runas: root
  #  AfterInstall:
  #    - location: shell/120.AfterInstall.sh
  #      timeout: 60
  #      runas: root
  ApplicationStart:
    - location: shell/130.ApplicationStart.sh
      timeout: 300
      runas: root
#  ValidateService:
#    - location: shell/140.ValidateService.sh
#      timeout: 300
#      runas: root