version: 0.0
os: linux
files:
  - source: /
    destination: /app/world_deploy
#permissions:  # CodeDeploy에서 EC2서버로 넘겨준 파일들을 모두 ec2-user권한을 갖도록 변경
#  - object: /
#    owner: ec2-user
#    group: ec2-user
#  - object: /app/world_deploy/shell/*.sh
#    mode: 744
#    owner: ec2-user
#    group: ec2-user
#    type:
#      - file
hooks:
#  ApplicationStop:
#    - location: shell/00.permissionSet.sh
#      timeout: 60
#      runas: ec2-user
#  BeforeInstall:
#    - location:
#  AfterInstall:
#    - location: shell/10.copySource.sh
#      timeout: 60
#      runas: root
##    - location: shell/11.syncS3.sh
##      timeout: 300
##      runas: ec2-user
#    - location: shell/12.cfCacheInvalidate.sh
#      timeout: 120
#      runas: root
  ApplicationStart:
    - location: shell/99.runAll.sh
      timeout: 60
      runas: root
#  ValidateService:
#    - location: shell/30.healthCheck.sh
#      timeout: 3600
#      runas: ec2-user