version: 0.0
os: linux
files:
  - source: source
    destination: /app/world_deploy
hooks:
#  ApplicationStop:
#    - location: shell/20.restartNginx.sh
#      timeout: 600
#      runas: ec2-user
#  BeforeInstall:
#    - location: shell/20.restartNginx.sh
  AfterInstall:
    - location: shell/10.copySource.sh
      timeout: 300
      runas: ec2-user
#    - location: shell/11.syncS3.sh
#      timeout: 300
#      runas: ec2-user
  ApplicationStart:
    - location: shell/20.restartNginx.sh
      timeout: 600
      runas: ec2-user
#  ValidateService:
#    - location: shell/30.healthCheck.sh
#      timeout: 3600
#      runas: ec2-user